name: Specflow workflow

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  specflowtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1'
      - uses: actions/cryptic-wizard/run-specflow-tests@v1.3.3
        with:
          test-assembly-path: SpecflowCalculator/bin/Release/net7.0
          test-assembly-dll: SpecflowCalculator.dll
          output-html: MyTestResults.html
